apiVersion: v1
kind: Service
metadata:
  name: angular-service
  labels:
    app: express-angular
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: express-angular
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
spec:
  selector:
    matchLabels:
      app: express-angular
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: express-angular
        tier: frontend
    spec:
      containers:
      - name: angular
        image: mawfia/angular:{{ .Values.version | default 1.0 }}
        ports:
          - name: angular
            containerPort: 80
